### ISSUE TITLE
Theming shinymanager login

### ISSUE THREAD

**Issue by pythiantech** [ColinFay/golemexamples#3]
I have a `{golem}` based `{shiny}` app that uses `{shinymanager}` for authentication. I have followed the example available here and have been able to successfully run my app. However, I need to add some custom css for the app's login page. In the non-golem version, of the app I have no issues to show my customized theme at login.  However it doesn't work when I do this in `run_app.R`:

```
run_app <- function(
  onStart = NULL,
  options = list(), 
  enableBookmarking = NULL,
  uiPattern = "/",
  ...
) {
  with_golem_options(
    app = shinyApp(
      ui = shinymanager::secure_app(app_ui,
                                    tags_top =
                                      tags$div(
                                        tags$h4("Welcome to Training Management System", style = "align:center; color:white;")
                                      ),
                                    theme = "style/style.css",
                                    enable_admin = TRUE),
      # ui = app_ui,
      server = app_server,
      onStart = onStart,
      options = options, 
      enableBookmarking = enableBookmarking, 
      uiPattern = uiPattern
    ), 
    golem_opts = list(...)
  )
}

```
I am not sure but I think the style.css (which contains other custom css applicable post login) is not available at the time of login. The h4 tag is visible as is the functionality of `enable_admin` but not the background image etc. which is in style.css. How can I get this going?

**Comment by statnmap** [comment]
You can have a look at how it works in {wedding}: https://github.com/ThinkR-open/wedding
You probably are looking for something like this one, with url relative to www:
 https://github.com/ThinkR-open/wedding/blob/31991841cf661ed471712b43ab877f6b0fe2c14f/R/run_app.R#L20

**Comment by pythiantech** [comment]
@statnmap thanks so much! I just needed to add `head_auth = golem_add_external_resources()`
